# Generated by Django 4.1.1 on 2022-09-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='name', max_length=255)),
                ('password', models.CharField(default='password', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('teamname', models.CharField(max_length=255)),
                ('event_registered', models.CharField(choices=[('treasure_hunt', 'Treasure Hunt'), ('prompt_poetry', 'Prompt Poetry'), ('noob_quiz', 'Noob Quiz'), ('word_games', 'Word Games'), ('just_a_minute_speech', 'Just A Minute Speech'), ('hindi_debate', 'Hindi Debate'), ('english_debate', 'English Debate'), ('netflix_and_quiz', 'Netflix and Quiz'), ('mela_quiz', 'Mela Quiz')], max_length=255)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='usermanagement.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EmailIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=255)),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.team')),
            ],
        ),
    ]
