# Generated by Django 4.1.1 on 2022-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event_registered',
            field=models.CharField(choices=[('prompt_poetry', 'Prompt Poetry'), ('noob_quiz', 'Noob Quiz'), ('word_games', 'Word Games'), ('hindi_debate', 'Hindi Debate'), ('english_debate', 'English Debate'), ('video_making_workshop', 'Video Making Workshop'), ('creative_writing_workshop', 'Creative Writing Workshop'), ('acting_workshop', 'Acting Workshop'), ('regional_literature_colloquium', 'Regional Literature Colloquium'), ('treasure_hunt', 'Treasure Hunt'), ('standup_comedy', 'Standup Comedy'), ('just_a_minute_speech', 'Just A Minute Speech'), ('prompt_based_character_re_enactment', 'Prompt Based Character Re-enactment'), ('mythology_quiz', 'Mythology Quiz'), ('theatre_performance', 'Theatre Performance'), ('english_author_book_signing', 'English Author Book Signing'), ('mela_quiz', 'Mela Quiz')], max_length=255),
        ),
    ]
