# Generated by Django 4.1.1 on 2022-09-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_team_event_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_interest',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
