# Generated by Django 4.1.1 on 2022-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_team_event_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
