# Generated by Django 4.1.1 on 2022-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_participant_college_name_alter_participant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='pass_type',
            field=models.CharField(choices=[('none', 'None'), ('events', 'Events Only'), ('flagship', 'Flagship only'), ('events_and_flagship', 'Events and Flagship')], default='none', max_length=255),
        ),
    ]
